sudo: required
services:
  - docker

before_install:
  - docker build -t akio63/react-test -f ./Dockerfile.dev ./client

script:
  - docker run akio63/react-test npm test -- --coverage

after_success:
  - docker build -t akio63/multi-client ./client
  - docker build -t akio63/multi-nginx ./nginx
  - docker build -t akio63/multi-server ./server
  - docker build -t akio63/multi-worker ./worker
  # login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to docekr hub
  - docker push akio63/multi-client
  - docker push akio63/multi-nginx
  - docker push akio63/multi-server
  - docker push akio63/multi-worker
